[package]
name = "flake-checker"
version = "0.1.9"
edition = "2021"

[dependencies]
chrono = { version = "0.4.25", default-features = false, features = [ "clock" ] }
clap = { version = "4.3.0", default-features = false, features = [ "derive", "env", "std", "wrap_help" ] }
handlebars = { version = "4.3.7", default-features = false }
is_ci = "1.1.1"
reqwest = { version = "0.11.18", default-features = false, features = [ "blocking", "rustls-tls-native-roots" ]}
serde = { version = "1.0.163", features = [ "derive" ] }
serde_json = { version = "1.0.96", default-features = false }
sha2 = { version = "0.10.6", default-features = false }
thiserror = "1.0.40"
