on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  check-allowed-refs:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - uses: DeterminateSystems/nix-installer-action@main

      - uses: DeterminateSystems/magic-nix-cache-action@main

      - name: Check allowed refs
        run: |
          nix develop --command cargo run --features check-allowed-refs -- --check-allowed-refs
