name: CI

on:
  pull_request:
  push:
    branches: [main]

jobs:
  check-clake:
    name: Check flake.lock
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v2
      - run: nix run
