name: CI

on:
  pull_request:
  push:
    branches: [main]

jobs:
  check-flake:
    name: Check flake.lock test
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v2
      - name: Check flake.lock
        run: |
          nix develop -c cargo run -- ./flake.bad.lock
