name: Flake checker CI

on:
  pull_request:
  push:
    branches: [main]

jobs:
  formatting-checks:
    name: Check Nix and Rust formatting
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Check Nix formatting
        run: nix develop -c check-nixpkgs-fmt
      - name: Check Rust formatting
        run: nix develop -c check-rustfmt

  check-flake-dirty:
    name: Check flake.lock test (dirty 😈)
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v2
      - name: Check flake.lock
        run: |
          nix develop -c cargo run -- ./flake.dirty.lock

  check-flake-clean:
    name: Check flake.lock test (clean 👼)
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v2
      - name: Check flake.lock
        run: |
          nix develop -c cargo run
