name: Release Branch

on:
  push:
    branches:
      # NOTE: make sure any branches here are also valid directory names,
      # otherwise creating the directory and uploading to s3 will fail
      - "main"

jobs:
  build:
    uses: ./.github/workflows/build.yaml

  release:
    needs: build

    concurrency: release
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write # In order to request a JWT for AWS auth
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create the artifacts directory
        run: rm -rf ./artifacts && mkdir ./artifacts

      - uses: actions/download-artifact@v4.1.7
        with:
          name: flake-checker-ARM64-macOS
          path: cache-binary-ARM64-macOS
      - name: Persist the cache binary
        run: cp ./cache-binary-ARM64-macOS/flake-checker ./artifacts/ARM64-macOS

      - uses: actions/download-artifact@v4.1.7
        with:
          name: flake-checker-X64-macOS
          path: cache-binary-X64-macOS
      - name: Persist the cache binary
        run: cp ./cache-binary-X64-macOS/flake-checker ./artifacts/X64-macOS

      - uses: actions/download-artifact@v4.1.7
        with:
          name: flake-checker-X64-Linux
          path: cache-binary-X64-Linux
      - name: Persist the cache binary
        run: cp ./cache-binary-X64-Linux/flake-checker ./artifacts/X64-Linux

      - uses: actions/download-artifact@v4.1.7
        with:
          name: flake-checker-ARM64-Linux
          path: cache-binary-ARM64-Linux
      - name: Persist the cache binary
        run: cp ./cache-binary-ARM64-Linux/flake-checker ./artifacts/ARM64-Linux

      - uses: DeterminateSystems/push-artifact-ids@main
        with:
          s3_upload_role: ${{ secrets.AWS_S3_UPLOAD_ROLE }}
          bucket: ${{ secrets.AWS_S3_UPLOAD_BUCKET }}
          directory: ./artifacts
          ids_project_name: flake-checker
          ids_binary_prefix: flake-checker
